<?php 

$page = $_REQUEST['page'];
$c = '';
if($page === '1'){
    $a = '{
        "status": 1,
        "page" : 1,
        "pageSize" : 20,
        "total" : 21,
        "data": [
            {
                "info_id": 1,
                "info_scene": "./upload/tg_index_02.png",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 2,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 3,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 4,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 11,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id":12,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 13,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 14,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 21,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 22,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 23,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 24,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 31,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 32,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 33,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 34,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 41,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 42,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 43,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 44,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 51,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 52,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 53,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            },
            {
                "info_id": 54,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            }
        ]
    }';
    echo json_decode(json_encode($a));
}
if($page === '2'){
    $a = '{
        "status": 1,
        "page" : 2,
        "pageSize" : 20,
        "total" : 21,
        "data": [
            {
                "info_id": 1,
                "info_scene": "'.$c.'",
                "info_scene_name": "机场",
                "info_team01": "./upload/25479170020671271_01.png",
                "info_team01_name": "女武神·系",
                "info_team02": "./upload/25479170020671271_01.png",
                "info_team02_name": "女武神·系1",
                "info_team03": "./upload/25479170020671271_01.png",
                "info_team03_name": "女武神·系2",
                "info_title": "史上最强队伍",
                "info_intro": "真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价真炎角色优缺点分析评价",
                "info_good": "123",
                "info_bad": "321",
                "info_comend": "1321",
                "info_ver": "1.8.0",
                "info_url": "./team-recommen-detail.html",
                "info_auth": "阿斯巴甜"
            }]
        }';
        echo json_decode(json_encode($a));
    }
?>